server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: FormulaireTest

  datasource:
    url: jdbc:mysql://localhost:3306/van?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: van
    password: vanpassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
